### ISSUE TITLE
Callback urls

### ISSUE THREAD

**Issue by edwinsmasher** [raiomido/laravel-mpesa-example#5]
My confirm and validate urls are not being triggered when i do a simulation

**Comment by raiomido** [comment]
Hi Smasher. It's not possible for me to know what the issue is so that I can help out.

But perhaps;
1. Try to push a dummy transaction before trying online.
2. I hope you are trying to do this online. Safaricom cannot push the transaction to localhost.

If the problem persists, you can contact me via my website, so I can help you to debug.
https://raiomido.com/#contact

Thanks!.

**Comment by edwinsmasher** [comment]
Works now with a new Test code they Gave me. Thankyou
